### ISSUE TITLE
Unable to tag portions of a string

### ISSUE THREAD

**Issue by kevinelliott** [tecoholic/ner-annotator#49] opened 2022-10-13 23:05 UTC
Looking to tag portions of a string.

```
AAABBBCCCDDDEEE.FFFFFF.GGGGGGGG
```

You cannot tag AAA, BBB, CCC, DDD, EEE, FFFFFF, or GGGGGGG. It will select the entire "word" automatically. An override to allow for fragmented tagging would be helpful.

**Comment by tecoholic** [comment] 2022-10-14 03:39
It is the intended behaviour. The software is created with the intention to tag the tokens - Tokens are individual "words". To make it easier to do that, selecting a single letter allows selecting the token. The effort required to do precise selection is way more than effort required to do rough selection. So, this won't be implemented. Sorry.

**Closed by tecoholic** 2022-10-14 03:39 UTC
